Update draft-ladd-privacypass-bbs.md
wbl/draft-ladd-bbs-privacypass pull request #8
Opened 2023-08-24 17:31 UTC by wbl

Solves Issue #7

2023-08-24 17:44 UTC, tfpauly requested changes
Thanks! Clearly some things as TODO, but that's OK. The main thing is to not stomp on type 3 =) 

There are several other places where `0x0003` is used. Can you fix all of those?

2023-08-24 17:54 UTC, tfpauly approved these changes

2023-08-29 07:53 UTC, BasileiosKal approved these changes
LGTM! Thank you!

2023-08-29 07:53 UTC, BasileiosKal commented on draft-ladd-privacypass-bbs.md
> +NiD: 32? TODO: check this
We need to add the Issuer configuration details to remove this TODO, but I do believe it will be 32 as well.

2023-09-01 14:42 UTC, merged